artifact_location: file:///C:/Users/Diogo/Desktop/Ano_Letivo_24_25/AOOP/AOOP_Computer_Vision_29259/epi-detector/runs/mlflow/797799910972457419
creation_time: 1747837405738
experiment_id: '797799910972457419'
last_update_time: 1747837405738
lifecycle_stage: active
name: /Shared/Ultralytics
