artifact_location: file:///C:/Users/Diogo/Desktop/Ano_Letivo_24_25/AOOP/AOOP_Computer_Vision_29259/epi-detector/runs/mlflow/0
creation_time: 1747837405726
experiment_id: '0'
last_update_time: 1747837405726
lifecycle_stage: active
name: Default
